# Generated by Django 4.1.4 on 2022-12-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('useremail', models.EmailField(max_length=254, verbose_name='Email')),
                ('username', models.CharField(max_length=25, verbose_name=' Name')),
                ('blogtitle', models.CharField(max_length=25, verbose_name='Title')),
                ('blogcontent', models.TextField(max_length=10000, verbose_name='Content')),
            ],
        ),
    ]
